mod_version=1.1.0
maven_group=com.notryken
archives_base_name=armorhud-percentages

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.1
loader_version=0.15.11
fabric_version=0.116.12+1.21.1
mixinsquared_version=0.2.0
armorhud_version=0.5.1+mc1.21
ukulib_version=1.4.1+1.21

loader_versions=>=0.15.11
minecraft_versions=>=1.21 <=1.21.1
java_versions=>=21
armorhud_versions=*
