plugins {
    id 'net.fabricmc.fabric-loom' version '1.15.+'
    id 'maven-publish'
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group
base { archivesName = project.archives_base_name + '-fabric-26.1-26.1.2' }

sourceSets {
    main {
        java { srcDirs rootProject.file('common/src/main/java') }
        resources { srcDirs rootProject.file('common/src/main/resources') }
    }
}

repositories {
    maven { name = 'Bawnorton'; url = 'https://maven.bawnorton.com/releases' }
    maven { name = 'uku'; url = 'https://maven.uku3lig.net/releases' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    include(implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:${project.mixinsquared_version}")))
    implementation files(rootProject.file('ukus-armor-hud-fabric-0.11.0+mc26.1.jar'))
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    final expandProps = [
        version: project.version,
        loader_versions: project.loader_versions,
        minecraft_versions: project.minecraft_versions,
        java_versions: project.java_versions,
        armorhud_versions: project.armorhud_versions,
    ]
    filesMatching('fabric.mod.json') { expand(expandProps) }
    inputs.properties(expandProps)
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

java {
    withSourcesJar()
    sourcesJar { duplicatesStrategy = DuplicatesStrategy.EXCLUDE }
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    inputs.property 'archivesName', project.base.archivesName
    from(rootProject.file('LICENSE.txt')) {
        rename { "LICENSE_${inputs.properties.archivesName}.txt" }
    }
}
