minecraft_version=26.1.2
loader_version=0.18.4
mod_version=1.1.0
maven_group=com.notryken
archives_base_name=armorhud-percentages
mixinsquared_version=0.3.3
ukulib_version=2.0.0+26.1-fabric
java_version=25
loader_versions=>=0.17.0
minecraft_versions=26.1-26.1.2
java_versions=>=21
armorhud_versions=0.11.0
fabric_version=0.148.2+26.1.2
